### ISSUE TITLE
How To Enable Scroll On Muya

### ISSUE THREAD

**Issue by libszen** [Jocs/muya-example#6]
Hello @jocs

This example use of Muya is very useful, thank you.

When the content within Muya exceeds the height of the window, the rest of the content is invisible. How can autoscroll be enabled on Muya?

I tried applying `overflow: auto` and `overflow: scroll` on the `app` div that Vue renders Muya into, but this did not work.

Thank you

**Comment by Jocs** [comment]
>When the content within Muya exceeds the height of the window, the rest of the content is invisible. How can autoscroll be enabled on Muya?

You need to give the editor a height, and set the style `overflow： auto`

<img width="546" alt="截屏2019-11-18下午3 13 30" src="https://user-images.githubusercontent.com/9712830/69031890-1a98c800-0a16-11ea-965a-6388fa15de43.png">

**Comment by libszen** [comment]
Thank You
